# Generated by Django 3.2 on 2021-05-25 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='user',
        ),
        migrations.AddField(
            model_name='character',
            name='subjects',
            field=models.ManyToManyField(to='main.Subject'),
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=20000)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paragraph', to='main.subject')),
            ],
        ),
    ]
