# Generated by Django 3.2 on 2021-05-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210525_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='subjects',
        ),
        migrations.AddField(
            model_name='subject',
            name='characters',
            field=models.ManyToManyField(to='main.Character'),
        ),
    ]
