# Generated by Django 3.2 on 2021-06-14 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210525_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ac',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='alignment',
            field=models.CharField(default='True Neutral', max_length=300),
        ),
        migrations.AddField(
            model_name='character',
            name='background',
            field=models.CharField(default='N/A', max_length=300),
        ),
        migrations.AddField(
            model_name='character',
            name='char_class',
            field=models.CharField(default='N/A', max_length=300),
        ),
        migrations.AddField(
            model_name='character',
            name='char_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='faction',
            field=models.CharField(default='N/A', max_length=300),
        ),
        migrations.AddField(
            model_name='character',
            name='inspiration',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='max_hp',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='prof_bonus',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.CharField(default='Human', max_length=300),
        ),
        migrations.AddField(
            model_name='character',
            name='speed',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subject'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=300)),
                ('isProf', models.BooleanField(default='false')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.character')),
            ],
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=300)),
                ('score', models.PositiveSmallIntegerField(default=10)),
                ('isProf', models.BooleanField(default='false')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.character')),
            ],
        ),
    ]
