# Generated by Django 3.2 on 2021-06-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210614_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='isProf',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='isProf',
            field=models.BooleanField(default='False'),
        ),
    ]
