# Generated by Django 3.2 on 2021-06-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210614_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='score',
            field=models.SmallIntegerField(default=10),
        ),
    ]
