# Generated by Django 3.2 on 2021-06-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_ability_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='isProf',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='character_pics'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='isProf',
            field=models.BooleanField(null=True),
        ),
    ]
