# Generated by Django 3.2 on 2021-06-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210617_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='isExpert',
            field=models.BooleanField(null=True),
        ),
    ]
