# Generated by Django 3.2 on 2021-07-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210617_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='current_hp',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='description',
            field=models.TextField(),
        ),
    ]
